### PR TITLE
Bundle update

### PR DESCRIPTION
**Pull request by eugenk**
This especially upgrades Sequel.

### CODE REVIEW

**Comment by phyrog** [comment]
If it helps debugging, the error only occurs if the database does not exist before running the `recreate` task.

**Comment by eugenk** [comment]
This only happens with Sequel >= 5.0.0. They seem to have changed how they connect to the database, too. If I use this version of the ontohub-models with the backend, drop the databases and try to create them again with `rails db:create`, it complains that the database doesn't exist.

**Comment by eugenk** [comment]
It's now ready for review.

**Comment by eugenk** [comment]
Rebased on master. There was a conflict in the database schema definition. Both changes only added code.

**Pull request merged**
