### PR TITLE
Update devise

### PR DESCRIPTION
**Pull request by ebolloff**

### CODE REVIEW

**Comment by phyrog** [comment]
Rbx does not seem to like the Sequel deprecations, so we should get rid of them before merging. See https://groups.google.com/forum/#!topic/sequel-talk/YXr7ykxdCGE for the discussion on this deprecation.

TL;DR seems to be: Replace `tablename__columnname` by `Sequel[:tablename][:columnname]` and `columnname___ascolumnname` by `Sequel[:columnname].as(:ascolumnname)`

**Comment by phyrog** [comment]
I think we should just remove the `have_column` tests completely. Sequel won't change its `:alias` handling on class table inheritance, and the gem we're using for this (https://github.com/openhood/rspec_sequel_matchers) has not been updated in a year, so unlikely that this will be fixed there. Another reason is, that these actually just test if the database is set up correctly, i.e. migrations ran correctly.

**Comment by ebolloff** [comment]
Travis seems to have some problems right now, I'll restart the job later.

**Comment by eugenk** [comment]
I added a commit to make it work again in Rubinius. Rubinus does not comply to Ruby 2.3 by not implementing `Class#deprecate_constant`. There is an old issue for it (mentioned in my commit).

**Pull request merged**
